### ISSUE TITLE
Investigate edit profile failures

### ISSUE THREAD

**Issue by rbillings** [mozilla/Affiliates-Tests#116]
Multiple failures on Affiliates on staging, no reported changes have been introduced.

https://webqa-ci.mozilla.com/job/affiliates.stage/107/HTML_Report/
https://webqa-ci.mozilla.com/job/affiliates.stage/121/HTML_Report/

**Comment by rbillings** [comment]
It seems to focus on this error:
E       WebDriverException: Message: Error forwarding the new session cannot find : Capabilities [{firefox_profile=UEsDBBQAAAAIAD19f0Yo4cn2VAMAA..., platform=MAC, javascriptEnabled=true, browserName=firefox, version=33}]

**Comment by rbillings** [comment]
Unable to reproduce locally or on saucelabs- failure is test being unable to find the cancel button on the edit profile modal.

**Comment by rbillings** [comment]
This is now impacting affiliates.dev jobs: https://webqa-ci.mozilla.com/job/affiliates.dev/69/HTML_Report/

**Comment by bobsilverberg** [comment]
For the record, these all appear to be `StaleElementReferenceException`s, which means there is an issue with timing in the jobs and how we are interacting with the element in question. I will try to investigate this this week, but anyone else is free to take it to investigate as well.

**Comment by bobsilverberg** [comment]
The test in question is `test_edit_profiles_website`
