### ISSUE TITLE
Upgrade py.test dependency to 2.7

### ISSUE THREAD

**Issue by davehunt** [mozilla/Affiliates-Tests#119]
We should update to the latest version of py.test. This can be done by updating the pinned versions of pytest, py, and any pytest plugins from `requirements.txt` to the latest versions. See https://github.com/mozilla/Addon-Tests/commit/bfa2336803debe57aaffaed4e1033e5d88f4c198 as an example.

Before submitting a pull request please test the changes locally. If you need any assistance, either comment here or ask in #mozwebqa on irc.mozilla.org. Details of how to get onto IRC can be found [here](https://wiki.mozilla.org/IRC).

**Comment by tarun1992** [comment]
I would like to do this task

**Comment by davehunt** [comment]
@tarun1992 I believe so, however it's worth checking and testing locally. When I did the original upgrade I removed the pinned versions locally, and let pip install the very latest. Then after I'd finished testing I added the pinned version according to what was installed.

**Comment by davehunt** [comment]
@tarun1992 are you still interested in working on this?

**Comment by davehunt** [comment]
Ah I see pull #122. Please reference the issue from your commit or pull request so that we can see the activity here.

**Comment by tarun1992** [comment]
Yes I am interested

**Comment by davehunt** [comment]
Fixed by https://github.com/mozilla/Affiliates-Tests/commit/675f4de8e864cf4986c9f30bd1fcf885c6e452bb
