### ISSUE TITLE
Update tests to bypass modal dialog

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Affiliates-Tests#123]
Affiliates.mozilla.org is in the process of being shutdown. There is a new modal dialog with information that informs users of this news.

The modal workflow breaks our test cases. The task is such.

* Update https://github.com/mozilla/Affiliates-Tests/blob/master/pages/start_page.py to click through this modal.

![screen shot 2015-05-18 at 3 08 27 pm](https://cloud.githubusercontent.com/assets/63193/7690398/7a4ed2e2-fd70-11e4-8afd-e62e902ed226.png)

**Comment by stephendonner** [comment]
So, looking at https://webqa-ci.mozilla.com/view/Affiliates/ - this does indeed break our prod [0] and stage [1] *.saucelabs jobs, but not our in-house (i.e. Selenium Grid) jobs:

* https://webqa-ci.mozilla.com/view/Affiliates/job/affiliates.prod/
* https://webqa-ci.mozilla.com/view/Affiliates/job/affiliates.stage/
* https://webqa-ci.mozilla.com/view/Affiliates/job/affiliates.dev/

What's the diagnosis/conclusion(s) on the difference(s) between these sets of jobs?  TBH, I'm guessing "viewport" (i.e. screen resolution) is one of them, I haven't, either, done the diagnosis.

**Comment by davehunt** [comment]
It looks like this modal dialog is not present on dev, so changing the tests to dismiss it will likely cause them to start failing on that environment. It looks like an initial click on the 'Sign In' link dismisses the dialog instead of opening the Persona popup. My guess is that when we run the tests on our grid we're clicking before the modal dialog is displayed.

**Comment by m8ttyB** [comment]
So, to fill in some knowledge gaps. This task is assigned to @tccharles. I notified the build master earlier this week of the cause of the failures and that updating the tests was not a high priority task for the core team to participate in (hence the `community` tag).

If you have questions or concerns please ping me in irc. This project is a very low priority for our team and a failing build for a few days is OK.

**Comment by m8ttyB** [comment]
Resolved in https://github.com/mozilla/Affiliates-Tests/commit/2316843547c0a7246a0da063f3e985cedff07222
