### ISSUE TITLE
Should we remove the accompanying page object for the Create Banner test?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Affiliates-Tests#132]
Thanks, @rbillings + @m8ttyB  for https://github.com/mozilla/Affiliates-Tests/pull/131 - should we also remove the page object, or at least the parts of it that test used?

https://github.com/mozilla/Affiliates-Tests/blob/master/pages/create_banner_page.py

**Comment by davehunt** [comment]
Closed by #133
